spring:
    datasource:
        url: jdbc:mysql://localhost:3306/allin?useSSL=false
        username: root
        password: 12345
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
#spring.jpa.show-sql: true
application:
    security:
        jwt:
            secret-key: F92BF449B4E4AB1CD8BA8AC1B634D123FQ2ACA132352522342342323545
            expiration: 86400000 #a day
            refresh-token:
                expiration: 604800000 # 7 day





